### ISSUE TITLE
devtool doesn't show up when option profile_name and har is specified

### ISSUE THREAD

**Issue by prozorecJP** [david-dick/firefox-marionette#10]
When Firefox::Marionette start with following options, Web devtool doesn't show up.

my $firefox = Firefox::Marionette->new (
  'profile_name' => 'marionette',
  'visible' => 1,
  'survive' => 1,
  'har' => 1
  );

**Comment by david-dick** [comment]
Thanks for the report.  I've committed a fix for the har issue.  There is a second issue here as well, which is specifying the survive parameter with a profile_name.  Can you confirm that the fix works without the survive parameter?

**Comment by prozorecJP** [comment]
I confirmed the fix works fine without "survive" option. Thank you.

**Comment by david-dick** [comment]
A fix for survive and profile name has been committed as well.  Feel free to re-open if this doesn't work for you.  Thanks for the bug report.
