### ISSUE TITLE
EXE_FILES

### ISSUE THREAD

**Issue by bokutin** [david-dick/firefox-marionette#11]
Hello.

https://github.com/david-dick/firefox-marionette/blob/9c9455eb80551aad5b3514ab8ac9d0d8f880aad4/Makefile.PL#L368

check-firefox-certificate-authorities and firefox-passwords are not included. Is this intentional?

Thanks,

**Comment by david-dick** [comment]
No it is not.  Good catch.

**Comment by bokutin** [comment]
build-bcd-for-firefox does not appear to be included.
