### ISSUE TITLE
current_chrome_window_handle and chrome_window_handle fail on FreeBSD 13.0

### ISSUE THREAD

**Issue by prozorecJP** [david-dick/firefox-marionette#12]
Hi.

I tried Firefox::Marionette on FreeBSD 13.0-p4 and I encountered the problem when calling current_chrome_window_handle and chrome_window_handle. It said "unknown command: WebDriver:GetCurrentChromeWindowHandle" and stopped.

This is the script I tried.

use strict;
use warnings;

use Firefox::Marionette;

my $firefox = Firefox::Marionette->new (
    'visible' => 1,
    'survive' => 1
  );

sleep (3);

my $cu_handle = eval { $firefox->current_chrome_window_handle() };
if ($@)
{
  print "current_chrome_window_handle failed $@\n";
}
my $ch_handle = eval { $firefox->chrome_window_handle() };
if ($@)
{
  print "chrome_window_handle failed $@\n";
}

Firefox version on FreeBSD 13 is 94.0.

**Comment by david-dick** [comment]
okay.  script works no issues on Fedora.  will try to replicate on FreeBSD.

**Comment by david-dick** [comment]
okay.  duplicated on FreeBSD 13

**Comment by david-dick** [comment]
Looks linked to this change [https://bugzilla.mozilla.org/show_bug.cgi?id=1729291](url)

**Comment by david-dick** [comment]
Still running testing, but [this patch](https://github.com/david-dick/firefox-marionette/commit/6f224a556c8e7dbd1c82bd493d8fd764e130e935) seems to work for me? Can you try it out and see if it works for you?

**Comment by prozorecJP** [comment]
Thank you, the patch works fine for me as well.
