### ISSUE TITLE
Question: how to specify identity file for ssh connection

### ISSUE THREAD

**Issue by prozorecJP** [david-dick/firefox-marionette#17]
Hello.

I'm trying remote firefox via ssh and I realized that there isn't any way to specify ssh private key identity file. Do you have plan to implement it?

**Comment by david-dick** [comment]
Hmmm... the thought was the user would pre-load keys into an agent.  Loading private keys should probably require being able to cope with a encrypted private key.  What was your use case for authentication?

**Comment by prozorecJP** [comment]
Thank you for explanation. I didn't think anything special about authentication so I just let Firefox::Marionette do all of them which require remote ssh connection. But I notice that ssh-agent can be used to prior to ssh connection now.

**Comment by david-dick** [comment]
I've directly mentioned ssh-agent in the documentation.  Thanks for the report.
