### ISSUE TITLE
Duplicate URL in ACKNOWLEDGEMENTS

### ISSUE THREAD

**Issue by jwilk** [david-dick/firefox-marionette#20]
In the [ACKNOWLEDGEMENTS section](https://github.com/david-dick/firefox-marionette#acknowledgements), "Marionette Protocol" and "Marionette Protocol" both point to the same URL: https://firefox-source-docs.mozilla.org/testing/marionette/marionette/index.html

**Comment by david-dick** [comment]
Thanks for that.  Fixed now.
