### ISSUE TITLE
Version 1.36 fails on macOS 13.2.1, Perl 5.36.0, Firefox 112.0.1

### ISSUE THREAD

**Issue by toreau** [david-dick/firefox-marionette#22]
Version 1.36 fixed many of the failed tests in 1.35, but there's one left:

```
t/01-marionette.t .. 1080/? 
#   Failed test 'Percentage visible is 100% for the username field:95.4545454545455'
#   at t/01-marionette.t line 4131.

```

**Comment by david-dick** [comment]
Can you provide any assistance as to how this is happening?  As previously, I cannot replicate this issue on my OS X platform or see the issue on the github OS X platform.  I would like you to run a script on your OS X machine and give me a screenshot of the result.

**Comment by toreau** [comment]
I cloned the repo and changed the test to check if `platform_name` is `mac` (not `darwin`);

```
if ($firefox->capabilities->platform_name eq 'mac') {
	ok($percentage >= 95, "Percentage visible is at least 95% for the username field: $percentage");
}
else {
	ok($percentage == 100, "Percentage visible is 100% for the username field: $percentage");
}
```

Not pretty, but it works. 😊

**Comment by david-dick** [comment]
that will do. Stand by.

**Comment by david-dick** [comment]
Okay, version 1.37 has been released.  It would be good to understand why this problem is happening, anything you could do to help with this would be most appreciated.

**Comment by toreau** [comment]
Successfully managed to install it from CPAN now. Great work! 😊

PS! Maybe create a macOS CI workflow?

**Comment by david-dick** [comment]
I've created this [one](https://github.com/david-dick/firefox-marionette/actions/runs/4843555256/workflow) and it's been running fine for a while.
