### ISSUE TITLE
ssh-auth-cmd-marionette refuses the command by "Unrecognisable command" on FreeBSD

### ISSUE THREAD

**Issue by prozorecJP** [david-dick/firefox-marionette#24]
Hello.

I haven't updated Firefox::Marionette for a while and I tried 1.37 today. I used ssh with profile name to set it up as before and encountered the problem.

> May 27 10:46:18 foxy ssh-auth-cmd-marionette[78502]: Unrecognisable command "ls -1 "/usr/local/lib/firefox"" with a quoted TMPDIR of "\/tmp" and a root directory regex of "(?^msx:(?^msx:(?:/var)?/tmp)/firefox_marionette_remote\w+)"

I dug out this issue and found that the content of @allowed_binary_directories for freebsd was changed in this update.

https://github.com/david-dick/firefox-marionette/commit/ec55db376993a943583a57e02dab9959ffe8edcc

Should %os_allowed_binary_directories should something like this?
            my %os_allowed_binary_directories = (
                freebsd   => '/usr/local/lib/firefox',

**Comment by david-dick** [comment]
Thanks for reporting this.  I've pushed a patch to github to fix the issue.  Expect a new release in a day or so.
