### ISSUE TITLE
Seems to hang under some 32 bit Strawberry Perl versions

### ISSUE THREAD

**Issue by twata1** [david-dick/firefox-marionette#26]
Hello,

For recently shipped Firefox-Marionettes, It seems to me that the test hangs under some 32 bit Strawberry Perl versions on Windows 7 32 bit as follows.
(I know Windows 7 is old OS.)

Strawberry Perl 5.26.1 32 bit
```
C:\home\bath1>cpan DDICK/Firefox-Marionette-1.48.tar.gz

(snip)

Running make test for DDICK/Firefox-Marionette-1.48.tar.gz
"C:\Strawberry\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harn
ess(0, 'blib\lib', 'blib\arch')" t/*.t
# Testing Firefox::Marionette 1.48
t/00.load.t ........ ok
# Version is Mozilla Firefox 115.4.0esr
# This firefox installation has 1 existing profiles
(hangs)
```

Strawberry Perl 5.24.0 32 bit
```
C:\home\west>cpan DDICK/Firefox-Marionette-1.48.tar.gz

(snip)

Running make test for DDICK/Firefox-Marionette-1.48.tar.gz
C:\"Strawberry\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test
_harness(0, 'blib\lib', 'blib\arch')" t/*.t
# Testing Firefox::Marionette 1.48
t/00.load.t ........ ok
# Version is Mozilla Firefox 115.4.0esr
# This firefox installation has 1 existing profiles
(hangs)
```

Strawberry Perl 5.18.4 32 bit
```
C:\home\journey>cpan DDICK/Firefox-Marionette-1.48.tar.gz

Running make test for DDICK/Firefox-Marionette-1.48.tar.gz
C:\"Strawberry\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test
(snip)

_harness(0, 'blib\lib', 'blib\arch')" t/*.t
# Testing Firefox::Marionette 1.48
t/00.load.t ........ ok
# Version is Mozilla Firefox 115.4.0esr
# This firefox installation has 1 existing profiles
(hangs)
```

The tests pass under Strawberry Perl 5.16.3 32 bit.
http://www.cpantesters.org/cpan/report/a6d7eafd-7058-1014-a358-b2c1e3396204

Thank you,

**Comment by david-dick** [comment]
Interesting.  Could you run `perl -Ilib t\01-marionette.t` and see if we get a bit more information about where the hang is?

**Comment by twata1** [comment]
Please wait.
(For some reason, it is not possible to switch the locale from Japanese to English, and it may take some time to translate error messages.)

**Comment by twata1** [comment]
Translated, this is supposed to output the message "An operation was attempted on something that is not a socket.".

Strawberry Perl 5.26.1 32 bit

```
C:\home\bath1\Firefox-Marionette-1.48>perl -Ilib t\01-marionette.t
# Version is Mozilla Firefox 115.4.0esr
ok 1 - Read 1 existing profiles
# This firefox installation has 1 existing profiles
ok 2 - Found default profile
ok 3 - No default waterfox profile
ok 4 - Read existing profile if any
ok 5 - Firefox::Marionette->new() threw an exception when launched with an incorrect path to a binary:Failed to execute '/fir
efox/is/not/here --version':An operation was attempted on something that is not a socket.
#
(hangs)
```

**Comment by david-dick** [comment]
Okay, I've replicated the behaviour.  Looks like an IPC::Open3 issue.

**Comment by david-dick** [comment]
okay, i've committed a patch to fix this.  if you could test this directly that would be great, otherwise, i'll release a new version in a day or so.

**Comment by twata1** [comment]
Now testing...

**Comment by twata1** [comment]
I think the test results are OK.
Here are build logs.
(These files are copy and pasted from the screen on the command prompt.)

[build-under-32-bit-SP5-26-1-on-Win7.log](https://github.com/david-dick/firefox-marionette/files/13398681/build-under-32-bit-SP5-26-1-on-Win7.log)
[build-under-32-bit-SP5-24-0-on-Win7.log](https://github.com/david-dick/firefox-marionette/files/13398682/build-under-32-bit-SP5-24-0-on-Win7.log)
[build-under-32-bit-SP5-18-4-on-Win7.log](https://github.com/david-dick/firefox-marionette/files/13398684/build-under-32-bit-SP5-18-4-on-Win7.log)

Thank you for resolving the issue!

**Comment by david-dick** [comment]
Excellent.  Thanks for the bug report and your assistance
