### ISSUE TITLE
how to get http status code?

### ISSUE THREAD

**Issue by 532910** [david-dick/firefox-marionette#31]
I'd like to make pdf, but only if 200 was returned.
If server returns 404 or 503 for example, pdf just prints page with "404" or "503" text.

**Comment by david-dick** [comment]
do you mean with the `$firefox->pdf()` method, or by going directly to a pdf url, like `$firefox->go("https://$hostname/$path.pdf);`

**Comment by 532910** [comment]
yep, `$firefix->pdf` method

**Comment by david-dick** [comment]
okay, probably the best option is to retrieve the page and then use the `$firefox->har()` method to extract the session and search for the url(s) that make up the page.  Does that work?

**Comment by 532910** [comment]
It sounds hard, there are no libarchive-har-perl in debian, trying to `Dumper( $firefox->pdf )` gives: `Perl: javascript error: ReferenceError: HAR is not defined`

Is it possible to get http status code from firefox after `Navigate` (and provide it as `$firefox->status_code()`)?

**Comment by david-dick** [comment]
libarchive-har-perl makes things a bit nicer, but what you are trying to achieve can be done with 
```#! /usr/bin/perl

use strict;
use warnings;
use Firefox::Marionette();

my $url = 'https://www.google.com/';
my $firefox = Firefox::Marionette->new(har => 1);
$firefox->go($url);
foreach my $entry (@{$firefox->har()->{log}->{entries}}) {
        if ($entry->{request}->{url} eq $url) {
                if ($entry->{response}->{status} == 200) {
                        warn "Printing successful page";
                        $firefox->pdf();
                }
        }
}
```

does that look ok?

**Comment by 532910** [comment]
yes, though I checked all statues:
```Perl
my @statuses = map { $_->{response}->{status} } @{$firefox->har->{log}->{entries}};
if( @statuses == grep { $_ eq 200 } @statuses ) ...
```

and https://github.com/david-dick/firefox-marionette/issues/32 ):

Thank you, @david-dick!
