### ISSUE TITLE
Perl: javascript error: ReferenceError: HAR is not defined

### ISSUE THREAD

**Issue by 532910** [david-dick/firefox-marionette#32]
With `new(har => 1)` I get `Perl: javascript error: ReferenceError: HAR is not defined` from time to time.

**Comment by 532910** [comment]
Yep, on linux, dbian stable.

**Comment by 532910** [comment]
https://github.com/firefox-devtools/har-export-trigger/issues/27

could this be related?

**Comment by david-dick** [comment]
probably not, as the `har => 1` argument to `Firefox::Marionette->new()` already automatically loads the devtools window, but I'm not having a lot of luck reproducing this one.  Do you have a script that can reliably reproduce the issue?

**Comment by david-dick** [comment]
I can reproduce the issue when loading a website that is very quick to load (a local nginx server returning a single html page).  Does that sound like it matches your environment?

**Comment by david-dick** [comment]
I've attached a small patch here to show a solution to the issue I described above.  If that matches your issue, could you apply the patch to your local install and see if it fixes the issue?
[har.patch](https://github.com/david-dick/firefox-marionette/files/13770999/har.patch)

**Comment by david-dick** [comment]
Any chance you can test this?  I've included the patch in the attached package
[Firefox-Marionette-1.50_01.tar.gz](https://github.com/david-dick/firefox-marionette/files/13896665/Firefox-Marionette-1.50_01.tar.gz)

**Comment by 532910** [comment]
Sure! Hope I'll test it this weekend.

**Comment by david-dick** [comment]
Just a ping on this one?

**Comment by david-dick** [comment]
I think this is fixed now.  There are new packages available on CPAN with the fixes included.  Please reopen this bug if you encounter this issue again.
