### ISSUE TITLE
selfie does not return a File::Temp object

### ISSUE THREAD

**Issue by eserte** [david-dick/firefox-marionette#5]
Contrary to what is written in the documentation, `selfie` does not return a `File::Temp` object, but just a filehandle. The difference between both is that for example the `filename` method is not available for the latter (which would be quite handy for some kind for things like `system("display", $selfie->filename)` without the need to create another temporary file).

It seems that a real `File::Temp` may be created using the following (no other code changes needed):
```
        my $handle = File::Temp->new(
	    TEMPLATE => File::Spec->catfile(
                File::Spec->tmpdir(), 'firefox_marionette_selfie_XXXXXXXXXXX'
            )
          )
```
(I can create a formal PR if this problem is accepted)

**Comment by david-dick** [comment]
Good catch.  Fix committed.
