### ISSUE TITLE
"This module does not work with snap." but it does

### ISSUE THREAD

**Issue by Domram** [david-dick/firefox-marionette#56]
When attempting to install
`cpanp -i Firefox::Marionette`
> Installing Firefox::Marionette (1.60)

I get the error:
> "We found a snapped firefox.  This module does not work with snap.  The ./setup-for-firefox-marionette-build.sh script contains an alternative way to setup firefox that works with this module"

**What is supposed to be the problem with snapped firefox?** I am running the most recent snap version of Firefox and **it is working**, at least with Firefox::Marionette v.1.22 installed via apt on Ubuntu 22.04. As far as a Firefox existent profile name is identified as an argument. e.g.:
`my $firefox = Firefox::Marionette->new(profile_name => 'marionette');`

It does however show the following warning:
> Use of uninitialized value in subroutine entry at /usr/share/perl5/Firefox/Marionette.pm line 2334.

which I fixed by replacing the following in Profile.pm
```            
        $profile_ini_directory =
          File::Spec->catdir( $home_directory, '.mozilla', 'firefox' );
    }
    return $profile_ini_directory;
```

with:
```        
        if ( -d "$home_directory/snap/firefox" ) { 
            $profile_ini_directory =
          File::Spec->catdir( $home_directory, 'snap', 'firefox', 'common', '.mozilla', 'firefox' );
        }
        else {
            $profile_ini_directory =
          File::Spec->catdir( $home_directory, '.mozilla', 'firefox' );
        }
    }
    return $profile_ini_directory;
```

**Comment by david-dick** [comment]
[This has been documented](https://metacpan.org/pod/Firefox::Marionette#UBUNTU-AND-FIREFOX-DELIVERED-VIA-SNAP).  Applying the fix here will work when using an existing profile, but NOT when using the default use case which is a new profile.  This also affects major sections of the test suite.

**Comment by Domram** [comment]
My fault for not reading that part of the documentation before.

Wouldn't be better than nothing to just trust the exec line of the shell script returned by `which firefox` ?

# Check for Snap installation:
sub is_snap_firefox_installed {
    return system("snap list firefox > /dev/null 2>&1") == 0;
}

# Examine Firefox executable:
sub is_likely_snap_firefox {
    my $firefox_path = `which firefox`;
    chomp $firefox_path;
    
    open my $fh, '<', $firefox_path or return 0;
    my $content = do { local $/; <$fh> };
    close $fh;
    
    return $content =~ /exec .*?\/snap\//;
}

# within the right subroutine:
if (is_snap_firefox_installed() && is_likely_snap_firefox()) {
	# etc.
}

**Comment by david-dick** [comment]
The issue here is these proposed changes will only work for established profiles, which is not the regular use case.  The regular use case requires access to /tmp or $TMPDIR, and snap is designed to stop access to /tmp.

Now we could define TMPDIR to point to a subdirectory under $HOME, when it's a snapped firefox and get things to work that way, but it seems like a lot of work to support what looks like a dubious piece of tech, that no-one else is doing.

Would you like to propose a patch that;

1. recognises a snapped firefox reliably and
2. creates and cleans up a $TMPDIR in $HOME?

**Comment by david-dick** [comment]
Also, this is what the setup-for-firefox-marionette-build.sh script is designed to do.  Produce a firefox version (and all the perl libraries) to be able to automate firefox with no worries.  Does that not work for you?

**Comment by Domram** [comment]
You’re probably right that supporting Snap may not be necessary, as fully supporting Snap seems to be more complex than I initially thought. I didn’t try the shell script you mentioned because I am used to the Snap version, and the solution I proposed above works well for my specific case. For now I will just automatically partially "fix it" locally with the tiny solution mentioned above.

**Comment by david-dick** [comment]
Okay, closing this for now
