### ISSUE TITLE
cannot drive existing profile

### ISSUE THREAD

**Issue by stuart-little** [david-dick/firefox-marionette#8]
I am running the following, after having created a throwaway new profile called `throw`:

```
#!/usr/bin/env perl
use warnings;
use v5.12;

use Firefox::Marionette;

my $url='https://www.google.com';
my $firefox = Firefox::Marionette->new(
    profile_name => 'throw',
    visible => 1,
    )->go($url);
sleep;
```
This opens up a browser window on the default startup page `Firefox` gives new profiles (screenshot [here](https://www.dropbox.com/s/d9twvlbpwe7qrv9/screenshot-from-2021-05-12-08-34-21.png?dl=0)), but hangs there. 

It never reaches `google.com`, and pegs one of my CPUs to 100%.

**Edit**

Actually, it hangs even without the `sleep;` directive at the end. Removing that last line makes no difference. 

Nor does setting my profile's homepage to blank. If I do that, then running that script results in a window hung on that initial blank page (again with a 100%-spinning CPU).

**Comment by stuart-little** [comment]
Here's what I get when running the following command in a clone of this repo:
```
$ perl -Ilib -MFirefox::Marionette -e 'my $firefox = Firefox::Marionette->new( debug => 1, visible => 1, profile_name => 'throw'); ' 
** firefox --version
** firefox -marionette -safe-mode -P throw
```
And it hangs there, again spinning up a CPU to full throttle. I have to kill the process with `Ctrl+C`.

**Comment by david-dick** [comment]
Ok.  I've verified this one.  Bit busy at the moment, will get to it on the weekend.

**Comment by stuart-little** [comment]
Thanks! Some more possibly-related info follows. 

I've also tried to use a copy of the existing profile instead, passing `profile` instead of `profile_name` (as per the [documentation](https://metacpan.org/pod/Firefox::Marionette::Profile#names)). So:
```
perl -Ilib -MFirefox::Marionette -e 'my $profile = Firefox::Marionette::Profile->existing('throw'); my $firefox = Firefox::Marionette->new( debug => 1, visible => 1, profile => $profile );  $firefox->go("https://www.google.com");  '
```
This again hangs and fails to load the `google` page (it just freezes on a blank page), but with more complaints:
```
** firefox --version
** firefox -marionette -safe-mode -profile /tmp/firefox_marionette_local_uMOkW5MQKkw/profile --no-remote --new-instance
/tmp/firefox_marionette_local_uMOkW5MQKkw/profile/prefs.js:9: prefs parse error: integer literal overflowed
/tmp/firefox_marionette_local_uMOkW5MQKkw/profile/prefs.js:56: prefs parse error: integer literal overflowed
/tmp/firefox_marionette_local_uMOkW5MQKkw/profile/prefs.js:57: prefs parse error: integer literal overflowed
/tmp/firefox_marionette_local_uMOkW5MQKkw/profile/prefs.js:58: prefs parse error: integer literal overflowed
/tmp/firefox_marionette_local_uMOkW5MQKkw/profile/prefs.js:59: prefs parse error: integer literal overflowed
/tmp/firefox_marionette_local_uMOkW5MQKkw/profile/prefs.js:63: prefs parse error: integer literal overflowed
/tmp/firefox_marionette_local_uMOkW5MQKkw/profile/prefs.js:67: prefs parse error: integer literal overflowed
/tmp/firefox_marionette_local_uMOkW5MQKkw/profile/prefs.js:92: prefs parse error: integer literal overflowed
/tmp/firefox_marionette_local_uMOkW5MQKkw/profile/prefs.js:123: prefs parse error: integer literal overflowed
/tmp/firefox_marionette_local_uMOkW5MQKkw/profile/prefs.js:176: prefs parse error: integer literal overflowed
/tmp/firefox_marionette_local_uMOkW5MQKkw/profile/prefs.js:237: prefs parse error: integer literal overflowed
```
I am having no trouble basing a profile off of this one with Python's `Selenium Webdriver`, via its [firefox_profile option](https://selenium-python.readthedocs.io/api.html#module-selenium.webdriver.firefox.webdriver). 

So I don't know why `prefs.js` would pose a problem if I try to peruse it through `Firefox::Marionette` instead.

**Comment by david-dick** [comment]
Just committed a fix for this.  Can you confirm this fixes the issues in this bug?

**Comment by stuart-little** [comment]
Yes, that did it. I

- removed the existing profile's `cookies.sqlite`
- ran the following command in the repo directory
```
perl -Ilib -MFirefox::Marionette -e 'my $firefox = Firefox::Marionette->new( debug => 1, visible => 1, profile_name => <PROFILE-NAME> );  $firefox->go("https://www.google.com");  '
```
- checked afterwards that a `cookies.sqlite` file was left behind, containing `google` cookies. 

So yeah, this seems to have fixed it, and I think it's safe to close this. Thank you!
